// Generated by scripts/build-font-catalog.mjs. Do not edit manually.
window.fontCatalog = {
  "serif": [],
  "sans-serif": [
    {
      "name": "Ubuntu Sans",
      "path": "fonts/sans-serif/UbuntuSans"
    }
  ],
  "script": [],
  "display": [],
  "monospace": [],
  "handwritten": [],
  "decorative": []
};
