// Generated by scripts/build-font-catalog.mjs. Do not edit manually.
window.fontCatalog = {
  "serif": [],
  "sans-serif": [
    {
      "name": "Ubuntu Sans",
      "path": "fonts/sans-serif/UbuntuSans",
      "variants": [
        {
          "filename": "UbuntuSans[wdth,wght].ttf",
          "style": "normal",
          "weight": 400
        },
        {
          "filename": "UbuntuSans-Italic[wdth,wght].ttf",
          "style": "italic",
          "weight": 400
        }
      ],
      "weightRange": [
        100,
        800
      ]
    }
  ],
  "script": [],
  "display": [],
  "monospace": [
    {
      "name": "Ubuntu Mono",
      "path": "fonts/monospace/ubuntumono",
      "variants": [
        {
          "filename": "UbuntuMono-Regular.ttf",
          "style": "normal",
          "weight": 400
        },
        {
          "filename": "UbuntuMono-Italic.ttf",
          "style": "italic",
          "weight": 400
        },
        {
          "filename": "UbuntuMono-Bold.ttf",
          "style": "normal",
          "weight": 700
        },
        {
          "filename": "UbuntuMono-BoldItalic.ttf",
          "style": "italic",
          "weight": 700
        }
      ],
      "weightRange": null
    }
  ],
  "handwritten": [],
  "decorative": []
};
