// Generated by scripts/build-font-catalog.mjs. Do not edit manually.
window.fontCatalog = {
  "serif": [
    {
      "name": "IBM Plex Serif",
      "path": "fonts/serif/ibmplexserif",
      "variants": [
        {
          "filename": "IBMPlexSerif-Thin.ttf",
          "style": "normal",
          "weight": 100
        },
        {
          "filename": "IBMPlexSerif-ThinItalic.ttf",
          "style": "italic",
          "weight": 100
        },
        {
          "filename": "IBMPlexSerif-ExtraLight.ttf",
          "style": "normal",
          "weight": 200
        },
        {
          "filename": "IBMPlexSerif-ExtraLightItalic.ttf",
          "style": "italic",
          "weight": 200
        },
        {
          "filename": "IBMPlexSerif-Light.ttf",
          "style": "normal",
          "weight": 300
        },
        {
          "filename": "IBMPlexSerif-LightItalic.ttf",
          "style": "italic",
          "weight": 300
        },
        {
          "filename": "IBMPlexSerif-Regular.ttf",
          "style": "normal",
          "weight": 400
        },
        {
          "filename": "IBMPlexSerif-Italic.ttf",
          "style": "italic",
          "weight": 400
        },
        {
          "filename": "IBMPlexSerif-Medium.ttf",
          "style": "normal",
          "weight": 500
        },
        {
          "filename": "IBMPlexSerif-MediumItalic.ttf",
          "style": "italic",
          "weight": 500
        },
        {
          "filename": "IBMPlexSerif-SemiBold.ttf",
          "style": "normal",
          "weight": 600
        },
        {
          "filename": "IBMPlexSerif-SemiBoldItalic.ttf",
          "style": "italic",
          "weight": 600
        },
        {
          "filename": "IBMPlexSerif-Bold.ttf",
          "style": "normal",
          "weight": 700
        },
        {
          "filename": "IBMPlexSerif-BoldItalic.ttf",
          "style": "italic",
          "weight": 700
        }
      ],
      "weightRange": null
    }
  ],
  "sans-serif": [
    {
      "name": "IBM Plex Sans",
      "path": "fonts/sans-serif/ibmplexsans",
      "variants": [
        {
          "filename": "IBMPlexSans[wdth,wght].ttf",
          "style": "normal",
          "weight": 400
        },
        {
          "filename": "IBMPlexSans-Italic[wdth,wght].ttf",
          "style": "italic",
          "weight": 400
        }
      ],
      "weightRange": [
        100,
        700
      ]
    },
    {
      "name": "IBM Plex Sans Arabic",
      "path": "fonts/sans-serif/ibmplexsansarabic",
      "variants": [
        {
          "filename": "IBMPlexSansArabic-Thin.ttf",
          "style": "normal",
          "weight": 100
        },
        {
          "filename": "IBMPlexSansArabic-ExtraLight.ttf",
          "style": "normal",
          "weight": 200
        },
        {
          "filename": "IBMPlexSansArabic-Light.ttf",
          "style": "normal",
          "weight": 300
        },
        {
          "filename": "IBMPlexSansArabic-Regular.ttf",
          "style": "normal",
          "weight": 400
        },
        {
          "filename": "IBMPlexSansArabic-Medium.ttf",
          "style": "normal",
          "weight": 500
        },
        {
          "filename": "IBMPlexSansArabic-SemiBold.ttf",
          "style": "normal",
          "weight": 600
        },
        {
          "filename": "IBMPlexSansArabic-Bold.ttf",
          "style": "normal",
          "weight": 700
        }
      ],
      "weightRange": null
    },
    {
      "name": "IBM Plex Sans Condensed",
      "path": "fonts/sans-serif/ibmplexsanscondensed",
      "variants": [
        {
          "filename": "IBMPlexSansCondensed-Thin.ttf",
          "style": "normal",
          "weight": 100
        },
        {
          "filename": "IBMPlexSansCondensed-ThinItalic.ttf",
          "style": "italic",
          "weight": 100
        },
        {
          "filename": "IBMPlexSansCondensed-ExtraLight.ttf",
          "style": "normal",
          "weight": 200
        },
        {
          "filename": "IBMPlexSansCondensed-ExtraLightItalic.ttf",
          "style": "italic",
          "weight": 200
        },
        {
          "filename": "IBMPlexSansCondensed-Light.ttf",
          "style": "normal",
          "weight": 300
        },
        {
          "filename": "IBMPlexSansCondensed-LightItalic.ttf",
          "style": "italic",
          "weight": 300
        },
        {
          "filename": "IBMPlexSansCondensed-Regular.ttf",
          "style": "normal",
          "weight": 400
        },
        {
          "filename": "IBMPlexSansCondensed-Italic.ttf",
          "style": "italic",
          "weight": 400
        },
        {
          "filename": "IBMPlexSansCondensed-Medium.ttf",
          "style": "normal",
          "weight": 500
        },
        {
          "filename": "IBMPlexSansCondensed-MediumItalic.ttf",
          "style": "italic",
          "weight": 500
        },
        {
          "filename": "IBMPlexSansCondensed-SemiBold.ttf",
          "style": "normal",
          "weight": 600
        },
        {
          "filename": "IBMPlexSansCondensed-SemiBoldItalic.ttf",
          "style": "italic",
          "weight": 600
        },
        {
          "filename": "IBMPlexSansCondensed-Bold.ttf",
          "style": "normal",
          "weight": 700
        },
        {
          "filename": "IBMPlexSansCondensed-BoldItalic.ttf",
          "style": "italic",
          "weight": 700
        }
      ],
      "weightRange": null
    },
    {
      "name": "IBM Plex Sans Devanagari",
      "path": "fonts/sans-serif/ibmplexsansdevanagari",
      "variants": [
        {
          "filename": "IBMPlexSansDevanagari-Thin.ttf",
          "style": "normal",
          "weight": 100
        },
        {
          "filename": "IBMPlexSansDevanagari-ExtraLight.ttf",
          "style": "normal",
          "weight": 200
        },
        {
          "filename": "IBMPlexSansDevanagari-Light.ttf",
          "style": "normal",
          "weight": 300
        },
        {
          "filename": "IBMPlexSansDevanagari-Regular.ttf",
          "style": "normal",
          "weight": 400
        },
        {
          "filename": "IBMPlexSansDevanagari-Medium.ttf",
          "style": "normal",
          "weight": 500
        },
        {
          "filename": "IBMPlexSansDevanagari-SemiBold.ttf",
          "style": "normal",
          "weight": 600
        },
        {
          "filename": "IBMPlexSansDevanagari-Bold.ttf",
          "style": "normal",
          "weight": 700
        }
      ],
      "weightRange": null
    },
    {
      "name": "IBM Plex Sans Hebrew",
      "path": "fonts/sans-serif/ibmplexsanshebrew",
      "variants": [
        {
          "filename": "IBMPlexSansHebrew-Thin.ttf",
          "style": "normal",
          "weight": 100
        },
        {
          "filename": "IBMPlexSansHebrew-ExtraLight.ttf",
          "style": "normal",
          "weight": 200
        },
        {
          "filename": "IBMPlexSansHebrew-Light.ttf",
          "style": "normal",
          "weight": 300
        },
        {
          "filename": "IBMPlexSansHebrew-Regular.ttf",
          "style": "normal",
          "weight": 400
        },
        {
          "filename": "IBMPlexSansHebrew-Medium.ttf",
          "style": "normal",
          "weight": 500
        },
        {
          "filename": "IBMPlexSansHebrew-SemiBold.ttf",
          "style": "normal",
          "weight": 600
        },
        {
          "filename": "IBMPlexSansHebrew-Bold.ttf",
          "style": "normal",
          "weight": 700
        }
      ],
      "weightRange": null
    },
    {
      "name": "IBM Plex Sans JP",
      "path": "fonts/sans-serif/ibmplexsansjp",
      "variants": [
        {
          "filename": "IBMPlexSansJP-Thin.ttf",
          "style": "normal",
          "weight": 100
        },
        {
          "filename": "IBMPlexSansJP-ExtraLight.ttf",
          "style": "normal",
          "weight": 200
        },
        {
          "filename": "IBMPlexSansJP-Light.ttf",
          "style": "normal",
          "weight": 300
        },
        {
          "filename": "IBMPlexSansJP-Regular.ttf",
          "style": "normal",
          "weight": 400
        },
        {
          "filename": "IBMPlexSansJP-Medium.ttf",
          "style": "normal",
          "weight": 500
        },
        {
          "filename": "IBMPlexSansJP-SemiBold.ttf",
          "style": "normal",
          "weight": 600
        },
        {
          "filename": "IBMPlexSansJP-Bold.ttf",
          "style": "normal",
          "weight": 700
        }
      ],
      "weightRange": null
    },
    {
      "name": "IBM Plex Sans KR",
      "path": "fonts/sans-serif/ibmplexsanskr",
      "variants": [
        {
          "filename": "IBMPlexSansKR-Thin.ttf",
          "style": "normal",
          "weight": 100
        },
        {
          "filename": "IBMPlexSansKR-ExtraLight.ttf",
          "style": "normal",
          "weight": 200
        },
        {
          "filename": "IBMPlexSansKR-Light.ttf",
          "style": "normal",
          "weight": 300
        },
        {
          "filename": "IBMPlexSansKR-Regular.ttf",
          "style": "normal",
          "weight": 400
        },
        {
          "filename": "IBMPlexSansKR-Medium.ttf",
          "style": "normal",
          "weight": 500
        },
        {
          "filename": "IBMPlexSansKR-SemiBold.ttf",
          "style": "normal",
          "weight": 600
        },
        {
          "filename": "IBMPlexSansKR-Bold.ttf",
          "style": "normal",
          "weight": 700
        }
      ],
      "weightRange": null
    },
    {
      "name": "IBM Plex Sans Thai",
      "path": "fonts/sans-serif/ibmplexsansthai",
      "variants": [
        {
          "filename": "IBMPlexSansThai-Thin.ttf",
          "style": "normal",
          "weight": 100
        },
        {
          "filename": "IBMPlexSansThai-ExtraLight.ttf",
          "style": "normal",
          "weight": 200
        },
        {
          "filename": "IBMPlexSansThai-Light.ttf",
          "style": "normal",
          "weight": 300
        },
        {
          "filename": "IBMPlexSansThai-Regular.ttf",
          "style": "normal",
          "weight": 400
        },
        {
          "filename": "IBMPlexSansThai-Medium.ttf",
          "style": "normal",
          "weight": 500
        },
        {
          "filename": "IBMPlexSansThai-SemiBold.ttf",
          "style": "normal",
          "weight": 600
        },
        {
          "filename": "IBMPlexSansThai-Bold.ttf",
          "style": "normal",
          "weight": 700
        }
      ],
      "weightRange": null
    },
    {
      "name": "IBM Plex Sans Thai Looped",
      "path": "fonts/sans-serif/ibmplexsansthailooped",
      "variants": [
        {
          "filename": "IBMPlexSansThaiLooped-Thin.ttf",
          "style": "normal",
          "weight": 100
        },
        {
          "filename": "IBMPlexSansThaiLooped-ExtraLight.ttf",
          "style": "normal",
          "weight": 200
        },
        {
          "filename": "IBMPlexSansThaiLooped-Light.ttf",
          "style": "normal",
          "weight": 300
        },
        {
          "filename": "IBMPlexSansThaiLooped-Regular.ttf",
          "style": "normal",
          "weight": 400
        },
        {
          "filename": "IBMPlexSansThaiLooped-Medium.ttf",
          "style": "normal",
          "weight": 500
        },
        {
          "filename": "IBMPlexSansThaiLooped-SemiBold.ttf",
          "style": "normal",
          "weight": 600
        },
        {
          "filename": "IBMPlexSansThaiLooped-Bold.ttf",
          "style": "normal",
          "weight": 700
        }
      ],
      "weightRange": null
    },
    {
      "name": "Ubuntu Sans",
      "path": "fonts/sans-serif/UbuntuSans",
      "variants": [
        {
          "filename": "UbuntuSans[wdth,wght].ttf",
          "style": "normal",
          "weight": 400
        },
        {
          "filename": "UbuntuSans-Italic[wdth,wght].ttf",
          "style": "italic",
          "weight": 400
        }
      ],
      "weightRange": [
        100,
        800
      ]
    }
  ],
  "script": [],
  "display": [],
  "monospace": [
    {
      "name": "IBM Plex Mono",
      "path": "fonts/monospace/ibmplexmono",
      "variants": [
        {
          "filename": "IBMPlexMono-Thin.ttf",
          "style": "normal",
          "weight": 100
        },
        {
          "filename": "IBMPlexMono-ThinItalic.ttf",
          "style": "italic",
          "weight": 100
        },
        {
          "filename": "IBMPlexMono-ExtraLight.ttf",
          "style": "normal",
          "weight": 200
        },
        {
          "filename": "IBMPlexMono-ExtraLightItalic.ttf",
          "style": "italic",
          "weight": 200
        },
        {
          "filename": "IBMPlexMono-Light.ttf",
          "style": "normal",
          "weight": 300
        },
        {
          "filename": "IBMPlexMono-LightItalic.ttf",
          "style": "italic",
          "weight": 300
        },
        {
          "filename": "IBMPlexMono-Regular.ttf",
          "style": "normal",
          "weight": 400
        },
        {
          "filename": "IBMPlexMono-Italic.ttf",
          "style": "italic",
          "weight": 400
        },
        {
          "filename": "IBMPlexMono-Medium.ttf",
          "style": "normal",
          "weight": 500
        },
        {
          "filename": "IBMPlexMono-MediumItalic.ttf",
          "style": "italic",
          "weight": 500
        },
        {
          "filename": "IBMPlexMono-SemiBold.ttf",
          "style": "normal",
          "weight": 600
        },
        {
          "filename": "IBMPlexMono-SemiBoldItalic.ttf",
          "style": "italic",
          "weight": 600
        },
        {
          "filename": "IBMPlexMono-Bold.ttf",
          "style": "normal",
          "weight": 700
        },
        {
          "filename": "IBMPlexMono-BoldItalic.ttf",
          "style": "italic",
          "weight": 700
        }
      ],
      "weightRange": null
    },
    {
      "name": "Ubuntu Mono",
      "path": "fonts/monospace/ubuntumono",
      "variants": [
        {
          "filename": "UbuntuMono-Regular.ttf",
          "style": "normal",
          "weight": 400
        },
        {
          "filename": "UbuntuMono-Italic.ttf",
          "style": "italic",
          "weight": 400
        },
        {
          "filename": "UbuntuMono-Bold.ttf",
          "style": "normal",
          "weight": 700
        },
        {
          "filename": "UbuntuMono-BoldItalic.ttf",
          "style": "italic",
          "weight": 700
        }
      ],
      "weightRange": null
    }
  ],
  "handwritten": [
    {
      "name": "Playwrite AU NSW",
      "path": "fonts/handwritten/playwriteaunsw",
      "variants": [
        {
          "filename": "PlaywriteAUNSW[wght].ttf",
          "style": "normal",
          "weight": 400
        }
      ],
      "weightRange": [
        100,
        400
      ]
    },
    {
      "name": "Playwrite AU QLD",
      "path": "fonts/handwritten/playwriteauqld",
      "variants": [
        {
          "filename": "PlaywriteAUQLD[wght].ttf",
          "style": "normal",
          "weight": 400
        }
      ],
      "weightRange": [
        100,
        400
      ]
    }
  ],
  "decorative": []
};
